// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"map-service/internal/conf"
	"map-service/internal/data"
	"map-service/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	goCloak := data.NewKeycloak(confData)
	keycloakAPI := data.NewKeyCloakAPI(confData, goCloak, logger)
	osrmClient := data.NewOSRMClient(confData)
	httpServer := server.NewHTTPServer(confServer, keycloakAPI, osrmClient, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
